// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actuary.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createActuary = `-- name: CreateActuary :one

INSERT INTO core_banking.actuary_info (
    employee_id,
    actuary_type,
    "limit",
    used_limit,
    need_approval
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    employee_id,
    actuary_type,
    "limit",
    used_limit,
    need_approval,
    created_at,
    updated_at
`

type CreateActuaryParams struct {
	EmployeeID   int64  `json:"employee_id"`
	ActuaryType  string `json:"actuary_type"`
	Limit        string `json:"limit"`
	UsedLimit    string `json:"used_limit"`
	NeedApproval bool   `json:"need_approval"`
}

// =============================================================================
// SQLC queries for actuary_info — bank-service
// Run `sqlc generate` from services/bank-service/ to regenerate Go code.
//
// Naming convention:
//
//	:one   → returns a single row  (sql.ErrNoRows if not found)
//	:exec  → returns no rows       (only checks for execution error)
//	:many  → returns []Row
//
// =============================================================================
// Inserts a new actuary_info record and returns the full row.
// employee_id must be unique; the caller is responsible for checking
// that the referenced employee exists in user-service.
func (q *Queries) CreateActuary(ctx context.Context, arg CreateActuaryParams) (CoreBankingActuaryInfo, error) {
	row := q.db.QueryRowContext(ctx, createActuary,
		arg.EmployeeID,
		arg.ActuaryType,
		arg.Limit,
		arg.UsedLimit,
		arg.NeedApproval,
	)
	var i CoreBankingActuaryInfo
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ActuaryType,
		&i.Limit,
		&i.UsedLimit,
		&i.NeedApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActuary = `-- name: DeleteActuary :exec
DELETE FROM core_banking.actuary_info
WHERE id = $1
`

// Removes the actuary_info record for the given PK.
// No-op (no error) when the id does not exist.
func (q *Queries) DeleteActuary(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteActuary, id)
	return err
}

const deleteActuaryByEmployeeId = `-- name: DeleteActuaryByEmployeeId :exec
DELETE FROM core_banking.actuary_info
WHERE employee_id = $1
`

// Removes the actuary_info record for the given employee_id.
// Idempotent: no error when no row matches.
func (q *Queries) DeleteActuaryByEmployeeId(ctx context.Context, employeeID int64) error {
	_, err := q.db.ExecContext(ctx, deleteActuaryByEmployeeId, employeeID)
	return err
}

const resetAllAgentsUsedLimit = `-- name: ResetAllAgentsUsedLimit :exec
UPDATE core_banking.actuary_info
SET used_limit  = '0.00',
    updated_at  = NOW()
WHERE actuary_type = 'AGENT'
`

// Atomically resets used_limit to '0.00' for every AGENT actuary.
func (q *Queries) ResetAllAgentsUsedLimit(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAllAgentsUsedLimit)
	return err
}

const getActuaryByEmployeeId = `-- name: GetActuaryByEmployeeId :one
SELECT
    id,
    employee_id,
    actuary_type,
    "limit",
    used_limit,
    need_approval,
    created_at,
    updated_at
FROM core_banking.actuary_info
WHERE employee_id = $1
`

// Returns the actuary_info row for a given employee_id.
// Used on every authenticated actuary request (JWT → employee_id lookup).
// Returns sql.ErrNoRows when the employee is not registered as an actuary.
func (q *Queries) GetActuaryByEmployeeId(ctx context.Context, employeeID int64) (CoreBankingActuaryInfo, error) {
	row := q.db.QueryRowContext(ctx, getActuaryByEmployeeId, employeeID)
	var i CoreBankingActuaryInfo
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ActuaryType,
		&i.Limit,
		&i.UsedLimit,
		&i.NeedApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActuaryById = `-- name: GetActuaryById :one
SELECT
    id,
    employee_id,
    actuary_type,
    "limit",
    used_limit,
    need_approval,
    created_at,
    updated_at
FROM core_banking.actuary_info
WHERE id = $1
`

// Returns the actuary_info row for the given PK.
// Returns sql.ErrNoRows when no matching record exists.
func (q *Queries) GetActuaryById(ctx context.Context, id int64) (CoreBankingActuaryInfo, error) {
	row := q.db.QueryRowContext(ctx, getActuaryById, id)
	var i CoreBankingActuaryInfo
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ActuaryType,
		&i.Limit,
		&i.UsedLimit,
		&i.NeedApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActuaries = `-- name: ListActuaries :many
SELECT
    id,
    employee_id,
    actuary_type,
    "limit",
    used_limit,
    need_approval,
    created_at,
    updated_at
FROM core_banking.actuary_info
WHERE ($1::VARCHAR IS NULL OR actuary_type = $1)
ORDER BY id
`

// Returns all actuary_info rows, with an optional filter on actuary_type.
// Pass a NULL sql.NullString to return all types (both SUPERVISOR and AGENT).
// sqlc.narg() generates a sql.NullString parameter so the IS NULL predicate
// works correctly from Go without resorting to raw *sql.DB queries.
//
// Note: user-side filters (email, first_name, last_name, position) are
// cross-service attributes resolved at the application layer after this query.
func (q *Queries) ListActuaries(ctx context.Context, actuaryType sql.NullString) ([]CoreBankingActuaryInfo, error) {
	rows, err := q.db.QueryContext(ctx, listActuaries, actuaryType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreBankingActuaryInfo{}
	for rows.Next() {
		var i CoreBankingActuaryInfo
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ActuaryType,
			&i.Limit,
			&i.UsedLimit,
			&i.NeedApproval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActuary = `-- name: UpdateActuary :one
UPDATE core_banking.actuary_info
SET
    actuary_type  = $2,
    "limit"       = $3,
    used_limit    = $4,
    need_approval = $5,
    updated_at    = NOW()
WHERE id = $1
RETURNING
    id,
    employee_id,
    actuary_type,
    "limit",
    used_limit,
    need_approval,
    created_at,
    updated_at
`

type UpdateActuaryParams struct {
	ID           int64  `json:"id"`
	ActuaryType  string `json:"actuary_type"`
	Limit        string `json:"limit"`
	UsedLimit    string `json:"used_limit"`
	NeedApproval bool   `json:"need_approval"`
}

// Replaces all mutable fields of an existing actuary_info record atomically.
// Bumps updated_at to the current timestamp.
// Returns sql.ErrNoRows when the given id does not exist.
func (q *Queries) UpdateActuary(ctx context.Context, arg UpdateActuaryParams) (CoreBankingActuaryInfo, error) {
	row := q.db.QueryRowContext(ctx, updateActuary,
		arg.ID,
		arg.ActuaryType,
		arg.Limit,
		arg.UsedLimit,
		arg.NeedApproval,
	)
	var i CoreBankingActuaryInfo
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ActuaryType,
		&i.Limit,
		&i.UsedLimit,
		&i.NeedApproval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
