// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// =============================================================================
	// SQLC queries for actuary_info — bank-service
	// Run `sqlc generate` from services/bank-service/ to regenerate Go code.
	//
	// Naming convention:
	//   :one   → returns a single row  (sql.ErrNoRows if not found)
	//   :exec  → returns no rows       (only checks for execution error)
	//   :many  → returns []Row
	// =============================================================================
	// Inserts a new actuary_info record and returns the full row.
	// employee_id must be unique; the caller is responsible for checking
	// that the referenced employee exists in user-service.
	CreateActuary(ctx context.Context, arg CreateActuaryParams) (CoreBankingActuaryInfo, error)
	// Removes the actuary_info record for the given PK.
	// No-op (no error) when the id does not exist.
	DeleteActuary(ctx context.Context, id int64) error
	// Removes the actuary_info record for the given employee_id. Idempotent.
	DeleteActuaryByEmployeeId(ctx context.Context, employeeID int64) error
	// Atomically resets used_limit to '0.00' for every AGENT actuary.
	ResetAllAgentsUsedLimit(ctx context.Context) error
	// Returns the actuary_info row for a given employee_id.
	// Used on every authenticated actuary request (JWT → employee_id lookup).
	// Returns sql.ErrNoRows when the employee is not registered as an actuary.
	GetActuaryByEmployeeId(ctx context.Context, employeeID int64) (CoreBankingActuaryInfo, error)
	// Returns the actuary_info row for the given PK.
	// Returns sql.ErrNoRows when no matching record exists.
	GetActuaryById(ctx context.Context, id int64) (CoreBankingActuaryInfo, error)
	// Returns all actuary_info rows, with an optional filter on actuary_type.
	// Pass a NULL sql.NullString to return all types (both SUPERVISOR and AGENT).
	// sqlc.narg() generates a sql.NullString parameter so the IS NULL predicate
	// works correctly from Go without resorting to raw *sql.DB queries.
	//
	// Note: user-side filters (email, first_name, last_name, position) are
	// cross-service attributes resolved at the application layer after this query.
	ListActuaries(ctx context.Context, actuaryType sql.NullString) ([]CoreBankingActuaryInfo, error)
	// Replaces all mutable fields of an existing actuary_info record atomically.
	// Bumps updated_at to the current timestamp.
	// Returns sql.ErrNoRows when the given id does not exist.
	UpdateActuary(ctx context.Context, arg UpdateActuaryParams) (CoreBankingActuaryInfo, error)
}

var _ Querier = (*Queries)(nil)
