// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	utils "banka-backend/services/user-service/internal/utils"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailPublisher is an autogenerated mock type for the EmailPublisher type
type MockEmailPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: event
func (_m *MockEmailPublisher) Publish(event utils.EmailEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(utils.EmailEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEmailPublisher creates a new instance of MockEmailPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailPublisher {
	mock := &MockEmailPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
