// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "banka-backend/services/bank-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockKreditRepository is an autogenerated mock type for the KreditRepository type
type MockKreditRepository struct {
	mock.Mock
}

// ApplyLatePaymentPenalty provides a mock function with given fields: ctx, kreditID, penaltyPercent
func (_m *MockKreditRepository) ApplyLatePaymentPenalty(ctx context.Context, kreditID int64, penaltyPercent float64) error {
	ret := _m.Called(ctx, kreditID, penaltyPercent)

	if len(ret) == 0 {
		panic("no return value specified for ApplyLatePaymentPenalty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64) error); ok {
		r0 = rf(ctx, kreditID, penaltyPercent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApproveKreditRequest provides a mock function with given fields: ctx, input
func (_m *MockKreditRepository) ApproveKreditRequest(ctx context.Context, input domain.ApproveKreditInput) (*domain.Kredit, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ApproveKreditRequest")
	}

	var r0 *domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApproveKreditInput) (*domain.Kredit, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ApproveKreditInput) *domain.Kredit); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ApproveKreditInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateKreditniZahtev provides a mock function with given fields: ctx, input
func (_m *MockKreditRepository) CreateKreditniZahtev(ctx context.Context, input domain.CreateKreditniZahtevInput) (*domain.KreditniZahtev, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateKreditniZahtev")
	}

	var r0 *domain.KreditniZahtev
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateKreditniZahtevInput) (*domain.KreditniZahtev, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateKreditniZahtevInput) *domain.KreditniZahtev); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KreditniZahtev)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateKreditniZahtevInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCredits provides a mock function with given fields: ctx, filter
func (_m *MockKreditRepository) GetAllCredits(ctx context.Context, filter domain.GetAllCreditsFilter) ([]domain.Kredit, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCredits")
	}

	var r0 []domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetAllCreditsFilter) ([]domain.Kredit, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetAllCreditsFilter) []domain.Kredit); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetAllCreditsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDueInstallments provides a mock function with given fields: ctx, asOf
func (_m *MockKreditRepository) GetDueInstallments(ctx context.Context, asOf time.Time) ([]domain.DueInstallment, error) {
	ret := _m.Called(ctx, asOf)

	if len(ret) == 0 {
		panic("no return value specified for GetDueInstallments")
	}

	var r0 []domain.DueInstallment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.DueInstallment, error)); ok {
		return rf(ctx, asOf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.DueInstallment); ok {
		r0 = rf(ctx, asOf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DueInstallment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, asOf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstallmentsByKredit provides a mock function with given fields: ctx, kreditID
func (_m *MockKreditRepository) GetInstallmentsByKredit(ctx context.Context, kreditID int64) ([]domain.Rata, error) {
	ret := _m.Called(ctx, kreditID)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallmentsByKredit")
	}

	var r0 []domain.Rata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Rata, error)); ok {
		return rf(ctx, kreditID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Rata); ok {
		r0 = rf(ctx, kreditID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Rata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, kreditID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKreditByID provides a mock function with given fields: ctx, id
func (_m *MockKreditRepository) GetKreditByID(ctx context.Context, id int64) (*domain.Kredit, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKreditByID")
	}

	var r0 *domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Kredit, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Kredit); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKreditniZahtevByID provides a mock function with given fields: ctx, id
func (_m *MockKreditRepository) GetKreditniZahtevByID(ctx context.Context, id int64) (*domain.KreditniZahtev, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKreditniZahtevByID")
	}

	var r0 *domain.KreditniZahtev
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.KreditniZahtev, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.KreditniZahtev); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KreditniZahtev)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKreditsByVlasnik provides a mock function with given fields: ctx, vlasnikID
func (_m *MockKreditRepository) GetKreditsByVlasnik(ctx context.Context, vlasnikID int64) ([]domain.Kredit, error) {
	ret := _m.Called(ctx, vlasnikID)

	if len(ret) == 0 {
		panic("no return value specified for GetKreditsByVlasnik")
	}

	var r0 []domain.Kredit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Kredit, error)); ok {
		return rf(ctx, vlasnikID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Kredit); ok {
		r0 = rf(ctx, vlasnikID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Kredit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, vlasnikID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingRequests provides a mock function with given fields: ctx, filter
func (_m *MockKreditRepository) GetPendingRequests(ctx context.Context, filter domain.GetPendingRequestsFilter) ([]domain.KreditniZahtev, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingRequests")
	}

	var r0 []domain.KreditniZahtev
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetPendingRequestsFilter) ([]domain.KreditniZahtev, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetPendingRequestsFilter) []domain.KreditniZahtev); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.KreditniZahtev)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetPendingRequestsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRetryInstallments provides a mock function with given fields: ctx, asOf
func (_m *MockKreditRepository) GetRetryInstallments(ctx context.Context, asOf time.Time) ([]domain.DueInstallment, error) {
	ret := _m.Called(ctx, asOf)

	if len(ret) == 0 {
		panic("no return value specified for GetRetryInstallments")
	}

	var r0 []domain.DueInstallment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.DueInstallment, error)); ok {
		return rf(ctx, asOf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.DueInstallment); ok {
		r0 = rf(ctx, asOf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DueInstallment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, asOf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkInstallmentFailed provides a mock function with given fields: ctx, rataID, nextRetry
func (_m *MockKreditRepository) MarkInstallmentFailed(ctx context.Context, rataID int64, nextRetry time.Time) error {
	ret := _m.Called(ctx, rataID, nextRetry)

	if len(ret) == 0 {
		panic("no return value specified for MarkInstallmentFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) error); ok {
		r0 = rf(ctx, rataID, nextRetry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessInstallmentPayment provides a mock function with given fields: ctx, input
func (_m *MockKreditRepository) ProcessInstallmentPayment(ctx context.Context, input domain.ProcessInstallmentInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ProcessInstallmentPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProcessInstallmentInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RejectKreditRequest provides a mock function with given fields: ctx, zahtevID
func (_m *MockKreditRepository) RejectKreditRequest(ctx context.Context, zahtevID int64) error {
	ret := _m.Called(ctx, zahtevID)

	if len(ret) == 0 {
		panic("no return value specified for RejectKreditRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, zahtevID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateKreditStatus provides a mock function with given fields: ctx, kreditID, status
func (_m *MockKreditRepository) UpdateKreditStatus(ctx context.Context, kreditID int64, status string) error {
	ret := _m.Called(ctx, kreditID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKreditStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, kreditID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockKreditRepository creates a new instance of MockKreditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKreditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKreditRepository {
	mock := &MockKreditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
