// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSMTPSender is an autogenerated mock type for the Sender type
type MockSMTPSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipient, subject, bodyHTML
func (_m *MockSMTPSender) Send(recipient string, subject string, bodyHTML string) error {
	ret := _m.Called(recipient, subject, bodyHTML)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(recipient, subject, bodyHTML)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSMTPSender creates a new instance of MockSMTPSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMTPSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMTPSender {
	mock := &MockSMTPSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
